name: Build project with Maven
on:
  pull_request:
  push:
    branches-ignore: [master]
  schedule:
  - cron: '2 2 * * 1' # run nightly master builds every monday 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Java setup
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: zulu
        cache: maven
    - name: Run Maven
      run: mvn -B clean install com.mycila:license-maven-plugin:check
    - name: Run CodeCov
      uses: codecov/codecov-action@v3

